import {PlantMedType, ProductType} from '../types';
import {UserType} from './UserType';
import {ReviewType} from './ReviewType';

export type RootStackParamList = {
  FAQ: undefined;
  Filter: undefined;
  SignIn: undefined;
  SignUp: undefined;
  Search: undefined;
  LogOut: undefined;
  MyProfile: undefined;
  Gravatar: undefined;
  Web: {url: string; title: string};
  UserCreationProcess: {user: UserType};
  MyAddress: undefined;
  NewPassword: {email?: string};
  Onboarding: undefined;
  EditProfile: undefined;
  OrderFailed: undefined;
  Plant_: {plant: ProductType};
  Plant: {plant: PlantMedType};
  OrderHistory: undefined;
  Shop: {title: string; products: ProductType[]};
  PlantMedList: {title: string; products: PlantMedType[]};
  MyPromocodes: undefined;
  TabNavigator: undefined;
  LeaveAReview: {productId: number};
  PaymentMethod: undefined;
  OrderSuccessful: undefined;
  ConfirmationCode: undefined;
  MyTestsAndDiagnostics: undefined;
  PrivacyPolicy: undefined;
  LanguageList: undefined;
  Reviews: {reviews: ReviewType[]};
  MyPromocodesEmpty: undefined;
  ModalScreen: undefined;
  Description: {description: string; title: string};
  CheckoutPaymentMethod: undefined;
  CheckoutShippingDetails: undefined;
  Filters: undefined;
  ForgotPasswordSentEmail: undefined;
  Checkout: undefined;
  InfoSaved: undefined;
  AccountCreated: undefined;
  PasswordChanged: undefined;
  AccountCreatedFailed: undefined;
  Source: {source: string[]; title: string};
  Sources: undefined;
  Prenium: undefined;
  TermsOfUse: undefined;
  PremiumActivated: undefined;
  MemberAccount: undefined;
  ManageSubscription: undefined;
  IsPreniumContent: undefined;

  /* VERIFICATION */
  SignUpAccountCreated: {email?: string; password?: string};

  /* VERIFICATION */
  VerifyEmail: {email?: string};
  VerifyPhone: {email?: string; phoneNumber?: string};
  SendPhoneOtp: undefined;
  SendEmailOtp: undefined;
  PhoneVerified: undefined;
  EmailVerified: undefined;
  DeleteAccount: undefined;
  VerifyEmailForgot: {email?: string};
  SendEmailOtpForgot: undefined;
  Product: {item: ProductType};
  PlantMed: {item: PlantMedType};
};
